# Copyright (C) 2020 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

version: 2

output: 'prefixed'

env:
  RELEASE_TIMESTAMP:
    sh: 'date +%Y%m%d%H%M%S'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'dependencies'
      - task: 'build'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  build:
    cmds:
      - task: 'build:assets'
      - task: 'build:static'

  build:assets:
    cmds:
      - 'npx buildstatic ./node_modules/assets/www.robotinaponcho.net ./public'
    desc: 'Build asset files'

  build:static:
    cmds:
      - 'npx buildstatic ./static_src ./public'
    desc: 'Build static files'

  clean:
    cmds:
      - 'rm -fr node_modules protected/vendor public release'
    desc: 'Delete all buildable files and third-party dependencies'

  dependencies:
    cmds:
      - task: 'dependencies:javascript'
      - task: 'dependencies:php'
    desc: 'Run all dependency-installing-related tasks'

  dependencies:javascript:
    cmds:
      # <http://www.tiernok.com/posts/2019/faster-npm-installs-during-ci/>
      - 'npm ci --prefer-offline --no-audit'
    env:
      CI: true
    desc: 'Install JavaScript dependencies for building, development, and testing'

  dependencies:php:
    cmds:
      - 'composer install --no-ansi --no-interaction --no-progress'
    desc: 'Install PHP dependencies for building, development, and testing'

  lint:
    cmds:
      - task: 'lint:javascript'
      - task: 'lint:php'
    desc: 'Run all linting-related tasks'

  lint:javascript:
    cmds:
      - 'npx eslint static_src/**/*.js'
    desc: 'Lint JavaScript files with ESLint'

  lint:php:
    cmds:
      - 'protected/vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff --diff-format=udiff'
    desc: 'Lint PHP scripts with PHP Coding Standards Fixer'

  release:
    cmds:
      - cmd: |
          {{ if .GIT_STATUS }}
            echo 'Working directory is dirty! Aborting.'
            exit 1
          {{ end }}
        silent: true
      - task: 'ci'
      - 'mkdir -p release'
      - 'tar --exclude ./protected/vendor -cvf release/release.tgz ./composer.* ./private/ ./protected/ ./public/'
      - 'envsubst < deployment.yml > release/release.yml'
    desc: 'Create release archive and metadata for deployment'
    env:
      RELEASE_GIT_SHA:
        sh: 'git log -n 1 --format=%H'
    vars:
      GIT_STATUS:
        sh: 'git status --porcelain'
