---
version: 2

output: prefixed

tasks:
  default:
    deps:
      - task: ci

  ci:
    cmds:
      - task: dependencies
      - task: build
      - task: lint
    desc: Run all CI-related tasks

  build:
    cmds:
      - task: build:assets
      - task: build:static

  build:assets:
    cmds:
      - node bin/buildstatic ./node_modules/assets/www.robotinaponcho.net ./public
    desc: Build asset files

  build:static:
    cmds:
      - node bin/buildstatic ./static_src ./public
    desc: Build static files

  clean:
    cmds:
      - rm -fr node_modules public
    desc: Delete all buildable files and JavaScript dependencies

  dependencies:
    cmds:
      - task: dependencies:javascript
      - task: dependencies:php
    desc: Run all dependency-installing-related tasks

  dependencies:javascript:
    cmds:
      # <http://www.tiernok.com/posts/2019/faster-npm-installs-during-ci/>
      - npm ci --prefer-offline --no-audit
    env:
      CI: true
    desc: Install JavaScript dependencies for building, development, and testing

  dependencies:php:
    cmds:
      - composer install --no-ansi --no-interaction --no-progress --no-suggest
    desc: Install PHP dependencies for building, development, and testing

  lint:
    cmds:
      - task: lint:javascript
      - task: lint:php
    desc: Run all linting-related tasks

  lint:javascript:
    cmds:
      - npx eslint bin/**
    desc: Lint JavaScript files with ESLint

  lint:php:
    cmds:
      - protected/vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff --diff-format=udiff
    desc: Lint PHP scripts with PHP Coding Standards Fixer
