# Copyright (C) 2022 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

- name: 'Ensure Git-repository-updating cron job exists'
  ansible.builtin.cron:
    cron_file: '{{ __release_crontab }}'
    job: 'nice -n 10 bash -c "{{ __release_base_directory }}/private/bin/update-git-repositories"'
    name: 'Update Git Repositories'
    user: 'www-data'
