# Rakefile for Damien Dart's personal website.
#
# Copyright (C) 2013, 2014 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

require "rubygems"
require "bundler/setup"
require "yaml"
Bundler.require(:default)

Haml::Filters::Scss.options[:cache] = false
Haml::Filters::Scss.options[:style] = :compressed

ERROR_CODES = %w{403 404 410}
OUTPUT_FILES = ERROR_CODES.map{ |code| "public/#{code}.html" } +
    ["public/index.html", "public/googlefb3645e0f9f23eaf.html", 
    "public/robots.txt", "public/crap/index.cgi"]

CLOBBER.include(OUTPUT_FILES)
task :default => OUTPUT_FILES

def tidyHTML(html_document)
  html_document = html_document.gsub(/^\s*$\n/, "")
  # HACK: Remove stray newlines from minified CSS which Sass 3.3 (and
  # newer) leaves behind.
  html_document = html_document.gsub(/}\s*(html|\.)/, "}\\1")
  return html_document
end

ERROR_CODES.each do |error_code|
  desc "Spit out the #{error_code} HTTP error document."
  file "public/#{error_code}.html" => FileList["public/_error.*"] do |task|
    puts "# Spitting out \"" + task.name + "\"."
    template = File.read("public/_error.haml")
    output = Haml::Engine.new(template, {:format => :html5,
        :escape_attrs => false, :attr_wrapper => "\""}).render(Object.new,
        :error_code => error_code)
    output = tidyHTML(output)
    File.open(task.name, "w") do |file|
      file.write(output)
    end
  end
end

desc "Spit out the homepage."
file "public/index.html" => FileList["public/_index.*"] do |task|
  puts "# Spitting out \"" + task.name + "\"."
  template = File.read("public/_index.haml")
  output = Haml::Engine.new(template, {:format => :html5,
      :escape_attrs => false, :attr_wrapper => "\""}).render
  output = output.gsub(/<!--.*-->\n/m, "")
  output = tidyHTML(output)
  output = Redcarpet::Render::SmartyPants.render(output)
  File.open(task.name, "w") do |file|
    file.write(output)
  end
end

desc "Spit out Google Webmaster Tools' Verification file."
file "public/googlefb3645e0f9f23eaf.html" do |task|
  puts "# Spitting out \"" + task.name + "\"."
  File.open(task.name, "w") do |file|
    file.write("google-site-verification: " + File.basename(task.name) + "\n")
  end
end

desc "Spit out \"robots.txt\"."
file "public/robots.txt" do |task|
  puts "# Spitting out \"" + task.name + "\"."
  File.open(task.name, "w") do |file|
    file.write("User-agent: *\n")
    (ERROR_CODES.map{ |code| "#{code}.html" } + ["assets/", "icons/",
        "git/"]).each do |path|
      file.write("Disallow: /#{path}\n")
    end
  end
end

desc "Spit out The Folder of Crap CGI script."
file "public/crap/index.cgi" => FileList["public/crap/_index.*"] do |task|
  puts "# Spitting out \"" + task.name + "\"."
  script = File.read("public/crap/_index.pl")
  script = script.gsub(/__DATA__.*$/m, "")
  template = File.read("public/crap/_index.haml")
  output = Haml::Engine.new(template, {:format => :html5,
      :escape_attrs => false, :attr_wrapper => "\""}).render
  output = tidyHTML(output)
  output = output.gsub(%r{^\s*//.*\n}, "")
  output = Redcarpet::Render::SmartyPants.render(output)
  # HACK: The SmartyPants parser doesn't like it when "HTMl::Template"'s tags
  # are used for HTML element attribute values.
  output = output.gsub(/&ldquo;/, "\"")
  File.open(task.name, "w") do |file|
    file.write(script)
    file.write("__DATA__\n")
    file.write(output)
  end
end
