#!/usr/bin/perl -w
#
# Copyright (C) 2013-2016 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

use strict;

use Image::Magick;
use LWP::Simple;

if (($#ARGV + 1) != 1) {
  print "Not enough operands\nUSAGE: $0 ASSET-FOLDER\n";
  exit(1);
}
(my $asset_folder = $ARGV[0]) =~ s|/\z||;
my $html = get("http://blog.robotinaponcho.net/") or die;
if ($html =~ m/data-bg-image="(.*)"/) {
  my $header = Image::Magick->new();
  my $header_retina = Image::Magick->new();
  $header->Read($1);
  $header->Resize(geometry => "320");
  $header->Write(filename => "$asset_folder/obtaincornhoop.png");
  $header_retina->Read($1);
  $header_retina->Resize(geometry => "640");
  $header_retina->Write(filename => "$asset_folder/obtaincornhoop\@2x.png");
  undef $header_retina;
}
