#!/bin/sh

USAGE=`cat <<USAGE;
USAGE: $(basename $0) ROBOTS-TXT-FILE REPOS-FOLDER
USAGE`
[ "$#" -lt 2 ] && { printf "Not enough operands\n$USAGE\n" >&2; exit 2; }
sed -e "/git/q" $1 > $1.tmp && cat $1.tmp > $1 && rm $1.tmp
for repo in $2/*.git; do
  ls -1p "$repo" | sed -e "s|^|Disallow: /$repo/|g" -e "/index.*/d" \
      -e "s|^Disallow: .*/git|Disallow: /git|g" >> $1
done
