#!/bin/sh
# Gitweb installation script for Damien Dart's personal website.
#
# Copyright (C) 2013, 2014 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

trap "rm -rf git-1.8.5.2" EXIT
USAGE=`cat <<USAGE;
USAGE: $(basename $0) HTDOCS-FOLDER PROTECTED-FOLDER [MAKE-COMMAND]
USAGE`
[ "$#" -lt 2 ] && { echo "Not enough operands\n$USAGE" >&2; exit 2; }
wget -O - https://github.com/git/git/archive/v1.8.5.2.tar.gz | tar -zxf -
(cd git-1.8.5.2 && ${3:-make} bindir="/usr/local/bin" \
    GITWEB_CONFIG="${2%/}/gitweb_config.perl" \
    GITWEB_CSS="/assets/gitweb.css" GITWEB_FAVICON="/assets/git-favicon.png" \
    GITWEB_JS="/assets/gitweb.js" \
    GITWEB_HOMETEXT="${2%/}/gitwebindextext.html" \
    GITWEB_LOGO="/assets/git-logo.png" \
    GITWEB_PROJECTROOT="${1%/}/git" \
    gitwebdir="${1%/}/git" gitweb install-gitweb &&
    mv ${1%/}/git/static/* ${1%/}/assets && rm -fr ${1%/}/git/static)
patch ${1%/}/git/gitweb.cgi <<'PATCH'
--- Original
+++ Modified
@@ -4066,7 +4066,7 @@
 <head>
 <meta http-equiv="content-type" content="$content_type; charset=utf-8"/>
 <meta name="generator" content="gitweb/$version git/$git_version$mod_perl_version"/>
-<meta name="robots" content="index, nofollow"/>
+<meta name="robots" content="noindex, nofollow"/>
 <title>$title</title>
 EOF
 	# the stylesheet, favicon etc urls won't work correctly with path_info
PATCH
cat << 'INDEX' > ${2%/}/gitwebindextext.html
Here are a bunch of read-only Git repository; at the moment the only
repositories here are mirrors of those found on my public GitHub
profile. These mirrors should be no more than an hour out of date,
unless the mirroring script I wrote broke.

-- <a href="http://www.robotinaponcho.net/">Damien</a></pre>
INDEX
cat << 'CONFIG' > ${2%/}/gitweb_config.perl
$site_name = "Damien's Git Repositories";
$feature{"avatar"}{"default"} = ["gravatar"];
$feature{"timed"}{"default"} = [1];
CONFIG
